export type Project = {
  slug: string;
  title: string;
  year: string;
  tags: string[];
  image: string | null;
  videoUrl: string | null;
  overview: string;
  problem: string;
  features: string[];
  liveUrl: string | null;
  githubUrl: string | null;
};

export const projects: Project[] = [
  {
    slug: "my-portfolio",
    title: "My Portfolio",
    year: "2026",
    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS", "GSAP"],
    image: "/images/my portfolio.png",
    videoUrl: "https://youtu.be/RRAAQlKkU6E",
    overview: `A premium, high-end interactive portfolio website built to showcase my selected works, skills, and professional journey. Focused on cutting-edge design, smooth GSAP animations, and responsive architecture.`,
    problem: `I needed a digital presence that reflects my capability to build premium, dynamic web experiences. A standard template wouldn't suffice; the portfolio itself had to serve as a proof of competence in advanced frontend engineering and motion design.`,
    features: [
      "Smooth scroll and parallax effects powered by GSAP",
      "Dynamic data-driven Works & Skills sections",
      "Fully responsive mobile-first architecture",
      "Custom UI components and premium typography",
      "Next.js App Router and optimized asset rendering"
    ],
    liveUrl: null,
    githubUrl: null,
  },
  {
    slug: "bztamiflow",
    title: "BztamiFlow",
    year: "2026",
    tags: ["Next.js 16", "React 19", "TypeScript", "Prisma", "PostgreSQL", "Tailwind CSS", "Google Gemini AI", "Resend", "Cloudinary"],
    image: "/images/BztamiFlow.png",
    videoUrl: "https://youtu.be/uNoI6R-joSM",
    overview: `BztamiFlow is a full-stack production-grade financial management platform built for the Moroccan banking ecosystem. Users manage multiple bank cards, track transactions, set savings goals, visualize spending analytics, and get personalized AI financial advice — all in MAD (Moroccan Dirham).`,
    problem: `Moroccan users had no unified platform to manage cards from multiple banks. Tracking spending, setting savings goals, and getting financial insights required switching between multiple banking apps with no cross-bank visibility or AI-powered guidance.`,
    features: [
      "Multi-card management across Moroccan banks",
      "Transaction tracking with categories and recurrence",
      "AI Financial Assistant powered by Google Gemini",
      "Savings goals with automated milestone alerts",
      "Budget management with spending limits",
      "Receipt scanning via Cloudinary + AI extraction",
      "PDF, CSV, Excel data exports",
      "Admin panel with revenue analytics",
      "FREE / STANDARD / PREMIUM subscription tiers",
      "Bilingual: English & French (next-intl)",
    ],
    liveUrl: null,
    githubUrl: "https://github.com/hermouchDev/bztami_flow",
  },
  {
    slug: "r-plus-telecom",
    title: "R+ Telecom",
    year: "2026",
    tags: ["Next.js", "Tailwind CSS", "Node.js", "Express", "Supabase", "Google Gemini AI", "JWT", "PDF Generation"],
    image: "/images/R+ Telecom.png",
    videoUrl: "https://youtu.be/GsBd6KsUvm0",
    overview: `A full-stack web platform built for a telecom agency working with Maroc Telecom. The platform simplifies telecom operations — from customer subscriptions to business analytics — giving the agency full visibility on performance.`,
    problem: `The agency managed customer subscriptions and orders manually with no digital system. There was no way to track performance, manage orders, or offer customers online subscription without physical interaction at the agency.`,
    features: [
      "Customers explore Fibre, ADSL & 5G offers",
      "Real-time price calculation",
      "Online subscription without physical interaction",
      "Advanced analytics dashboard",
      "Order & subscription management system",
      "AI assistant powered by Google Gemini",
      "Automated PDF contract generation",
      "Email system integration",
      "Secure JWT authentication",
    ],
    liveUrl: null,
    githubUrl: null,
  },
  {
    slug: "eventx",
    title: "EventX",
    year: "2026",
    tags: ["React 19", "Vite", "Node.js", "Express", "MongoDB", "Tailwind CSS 4", "Docker", "JWT", "Microservices"],
    image: "/images/EventX.png",
    videoUrl: "https://youtu.be/d68L75wGUO4",
    overview: `EventX is a full-stack Event Management platform built with a Microservices Architecture. Split into Auth, Events, and Registration services orchestrated with Docker Compose for scalability and seamless deployment.`,
    problem: `Building a monolithic event platform creates bottlenecks at scale — one service failing brings down the entire app. The challenge was designing a decoupled, containerized system where each service operates independently and communicates securely across Docker networks.`,
    features: [
      "Microservices: Auth, Events, Registrations",
      "JWT authentication with Bcrypt",
      "Docker + Docker Compose orchestration",
      "Inter-service API communication",
      "Event creation and registration flows",
      "Responsive UI with Tailwind CSS 4",
    ],
    liveUrl: null,
    githubUrl: null,
  },
  {
    slug: "hermouch-store",
    title: "Hermouch Store",
    year: "2025",
    tags: ["React 19", "Vite", "React Router", "Bootstrap 5", "BlurHash"],
    image: "/images/Hermouch Store.png",
    videoUrl: "https://youtu.be/EbVIS9QWEiE",
    overview: `The official front-end for HERMOUCH, a luxury streetwear brand online store. Built with React and Vite with a full product catalog, shopping cart, and checkout flow.`,
    problem: `A luxury streetwear brand needed a digital storefront that matched its premium identity — fast image loading, smooth interactions, and a clean shopping experience across all devices.`,
    features: [
      "Product catalog with category filtering",
      "Shopping cart with size & quantity management",
      "Checkout flow with order confirmation",
      "BlurHash for smooth image loading",
      "Hover animations and transitions",
      "Fully responsive design",
    ],
    liveUrl: "https://hermouchstore.vercel.app/",
    githubUrl: "https://github.com/hermouchDev/Hermouch-Store",
  },
  {
    slug: "todo-list",
    title: "ToDo List",
    year: "2025",
    tags: ["React 19", "Vite", "Zustand", "PHP", "MySQL", "Bootstrap 5", "Drag & Drop API"],
    image: "/images/ToDo List.png",
    videoUrl: "https://youtu.be/3UVtajyJf4k",
    overview: `A full-stack ToDo List app upgraded from a basic CRUD app to a feature-rich task manager with Kanban board, drag-and-drop, and a PHP REST API backend with MySQL.`,
    problem: `The original version was a simple list with no visual workflow. The upgrade needed to introduce a Kanban view, drag-and-drop across statuses, mobile touch support, and a proper backend with timestamp tracking — without rebuilding from scratch.`,
    features: [
      "List view + Kanban board",
      "HTML5 Drag & Drop (desktop + mobile touch)",
      "Status workflow: Todo → In Progress → Done",
      "Automatic timestamps per state",
      "PHP REST API with PDO + MySQL",
      "Zustand state management",
      "Congratulations sound on task completion",
    ],
    liveUrl: "https://pay-together-02.vercel.app/",
    githubUrl: "https://github.com/hermouchDev/Pay-Together",
  },
  {
    slug: "hermouch-pizza",
    title: "Hermouch Pizza",
    year: "2025",
    tags: ["React 19", "CSS3", "Flexbox", "Grid"],
    image: "/images/Hermouch Pizza.png",
    videoUrl: "https://youtu.be/PR2v8QkYs0s",
    overview: `A modern fully responsive pizza menu web app built with React 19 and CSS3. Features a clean UI, smooth hover effects, dynamic menu display, and a real-time hours indicator showing if the restaurant is currently open.`,
    problem: `First React project — the goal was to master component-based architecture, state management, responsive layouts with Grid and Flexbox, and mobile-first design principles.`,
    features: [
      "Dynamic menu display",
      "Real-time open/closed hours indicator",
      "Smooth hover effects",
      "Fully responsive (mobile-first)",
      "Component-based React architecture",
    ],
    liveUrl: "https://hermouch-pizza.vercel.app/",
    githubUrl: "https://github.com/hermouchDev/Pizza-menu",
  },
  {
    slug: "travel-list",
    title: "Travel Packing List",
    year: "2025",
    tags: ["React 19", "React Hooks", "JavaScript"],
    image: "/images/Travel List.png",
    videoUrl: "https://youtu.be/lC_-Y3Y7x7Q",
    overview: `A travel packing list app built with React. Add travel items with quantities, mark them as packed, sort by different criteria, and track packing progress with a clean minimal UI.`,
    problem: `Practicing React Hooks, component composition, prop drilling, and UX improvements like duplicate prevention, empty states, sorting, and delete confirmation.`,
    features: [
      "Add items with quantities",
      "Mark items as packed",
      "Sort by input order, description, or status",
      "Duplicate entry prevention",
      "Delete confirmation",
      "Packing progress indicator",
    ],
    liveUrl: "https://mini-travel-list-app.vercel.app/",
    githubUrl: "https://github.com/hermouchDev/Mini-Travel-List-App",
  },
  {
    slug: "pay-together",
    title: "Pay Together",
    year: "2025",
    tags: ["React 19", "React Hooks", "CSS"],
    image: "/images/Pay Together.png",
    videoUrl: "https://youtu.be/x49yPEarEdk",
    overview: `A bill splitting web app built with React. Add friends with names and photos, enter any bill amount, choose who paid, and the app calculates exactly how much each person owes.`,
    problem: `Splitting bills in group situations (dinners, trips, shared expenses) is always awkward and error-prone when done manually. The app makes it instant, fair, and visual.`,
    features: [
      "Add friends with name and photo",
      "Enter bill amount and select who paid",
      "Automatic split calculation",
      "Responsive mobile-first design",
      "Clean minimal UI",
    ],
    liveUrl: "https://lnkd.in/ecVxu6Gk",
    githubUrl: "https://lnkd.in/eZ45ZgAn",
  }
];
